version: '3.8'

services:
  frontend-api:
    build: ./frontend-api
    container_name: frontend-api
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - rabbitmq
    env_file:
      - ./frontend-api/.env

  admin-api:
    build: ./admin-api
    container_name: admin-api
    ports:
      - "8001:8001"
    depends_on:
      - mongo
      - rabbitmq
    env_file:
      - ./admin-api/.env

  postgres:
    image: postgres:13
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: library_frontend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: examplepassword


  mongo:
    image: mongo:4.4
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    
      - "15672:15672"  
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_data:
  mongo_data:
  rabbitmq_data:
